### PR TITLE
Async migration

### PR DESCRIPTION
**Pull request by harryadel**
In progress... Gonna wrap things up in a couple of days :crossed_fingers: 
I'm trying now to get the tests to pass flawlessly.

### CODE REVIEW

**Comment by msavin** [comment]
Hey looks great so far! Thanks for the effort.

 Are you planning to fork or looking to merge?

**Comment by harryadel** [comment]
To merge of course! It's just I've not heard from you ever since I started this PR and I wanted to take it for a test run. Please review and if it's all good let's do a beta release and see how it goes from there.

**Comment by harryadel** [comment]
@msavin AFAIK, this is ready. At our application we only use it twice to run very simple jobs. That's why there might be a few bugs lingering here or there so I need others to give it a test run.

**Comment by StorytellerCZ** [comment]
I will be take this PR for a test run soon.

**Comment by bomb-on** [comment]
First to say thank you all for all the effort in migrating this amazing package! I just wonder if there's any progress with testing and merging, would really like to see it available for Meteor 3!

**Comment by vparpoil** [comment]
hi @harryadel, I've been using your fork and I have some warnings in server console :
> TypeError: Promise.await is not a function
> at process (packages/harry97:sjobs/server/imports/actions/execute/process.js:15:29)
> at execute (packages/harry97:sjobs/server/imports/actions/execute/index.js:12:25)
> at processTicksAndRejections (node:internal/process/task_queues:95:5)

Is this misconfiguration on my side ?

**Comment by vparpoil** [comment]
My bad ! I did indeed cloned Storyteller version but I had `harry97:sjobs` in my package file 🤦 
Seems to work like a charm now !

**Comment by StorytellerCZ** [comment]
OK, I'll get on Harry to merge my changes so that we can then merge this here.

**Comment by harryadel** [comment]
@vparpoil @StorytellerCZ I just merged in your contributions guys, thank you for your amazing efforts. I've been busy the last week and couldn't free up time to OSS.

**Comment by harryadel** [comment]
What's the current status on this?

**Comment by StorytellerCZ** [comment]
@msavin I think we can publish a beta or rc with this. I'm using this in production without issues.

**Comment by JanMP** [comment]
Runs fine locally, but It doesn't start on my DO deploy. It writes jobs_data and the entries look fine but it just won't start any of the jobs and jobs_dominator_3 stays empty (after quite a bit more than 5 minutes).

**Comment by vparpoil** [comment]
> Runs fine locally, but It doesn't start on my DO deploy. It writes jobs_data and the entries look fine but it just won't start any of the jobs and jobs_dominator_3 stays empty (after quite a bit more than 5 minutes).

I am experiencing the same issue : 
- with Meteor 2.16 and this version [d559ae0](https://github.com/msavin/SteveJobs/pull/112/commits/d559ae0e6a189c40e0a02e914a207072e214a01f)
- with Meteor 3. and this version [96ad864](https://github.com/msavin/SteveJobs/pull/112/commits/96ad8642e81b6c32d7bf0fbd837f2ae49fc77d4a)

In my Meteor 2.16 app, where dominator existed, it doesn't seem to update, here is my data right now (app has been restarted multiple times since then)
```
{
    "_id" : "n4EctdJafj7Qrj95o",
    "serverId" : "vPKvvuna48zwJTfNi",
    "created" : ISODate("2024-09-03T08:44:02.599+0000"),
    "lastPing" : ISODate("2024-09-04T07:49:59.906+0000")
}
```
In my Meteor 3 app, there is no data in `jobs_dominator_3` collection

I will investigate further, any hint much appreciated !

**Comment by vparpoil** [comment]
I think I fixed it adding some await that were missing in dominator's code : https://github.com/harryadel/SteveJobs/pull/3
@harryadel up to you for merging. 
I haven't run the test suite, only tested end to end on my Meteor 2.16 deployment

**Comment by harryadel** [comment]
@vparpoil Thank you Victor. I had just merged your PR. Please let me know if you run into any other problems, thanks!

**Comment by vparpoil** [comment]
@harryadel Further tests and modifications to be merged here if they look good to you : https://github.com/harryadel/SteveJobs/pull/4

**Comment by StorytellerCZ** [comment]
I think we have everything. How is everyone feeling about the state of things so far?

**Comment by vparpoil** [comment]
We have been running it in production for simple cases (some daily jobs that replicate from day to day) without issues. I will update to add the last commit with job resolution, thanks @StorytellerCZ 
I think this is ready for publication, at least of a RC

**Comment by msavin** [comment]
Huge thanks guys! I merged it and published to Atmosphere with a credit to you guys!

**Comment by StorytellerCZ** [comment]
Thanks a lot for the merge, but I don't see v5 on Atmosphere. If there is an issue with release just publishing for Meteor v3 is fine.

**Comment by harryadel** [comment]
@msavin I don't see a new release on packosphere
https://packosphere.com/msavin/sjobs
I know you may be busy but if you can give it this one last push, it'd be awesome. Thank you, Max!

**Pull request merged**
